repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.2
  hooks:
    # Run the linter on non-imports
    - id: ruff
      args: ["--fix"]
    # Run the linter on imports
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      args: [ --config=ruff.toml ]